---
victorialogs_vars:
  kubernetes:
    helm:
      chart:
        alias: vls
        name: victoria-logs-single
        version: v0.8.10
      repository:
        name: helm-charts
        org: VictoriaMetrics
        url: https://victoriametrics.github.io
